name: Auto IPTV Premium Hunter

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests urllib3

    - name: Run Premium Hunter
      run: python main.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # السطر التالي يضمن حفظ مجلد البلايليست الجديد بالكامل
        git add playlists/
        git commit -m "🚀 تحديث القنوات العربية والعالمية والمدفوعة" || exit 0
        git push
